=== sergiomalv/sew/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="medio-transporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="inicio-ruta" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="personas-adecuadas" />
				<xs:element ref="lugar-inicio" />
				<xs:element ref="direccion-inicio" />
				<xs:element ref="coordenadas" />
				<xs:element ref="referencias-bibliografia" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tipo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="tipo" type="xs:string" />
	<xs:element name="medio-transporte" type="xs:string" />
	<xs:element name="inicio-ruta" type="xs:dateTime" />
	<xs:element name="duracion" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="personas-adecuadas" type="xs:string" />
	<xs:element name="lugar-inicio" type="xs:string" />
	<xs:element name="direccion-inicio" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud" type="xs:float" use="required" />
					<xs:attribute name="latitud" type="xs:float" use="required" />
					<xs:attribute name="altitud" type="xs:integer" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:float" />
	<xs:element name="latitud" type="xs:float" />
	<xs:element name="altitud" type="xs:integer" />
	<xs:element name="referencias-bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia-bibliografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia-bibliografia" type="xs:string" />
	<xs:element name="recomendacion" >
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"></xs:minInclusive>
				<xs:maxInclusive value="10"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre-hito" />
				<xs:element ref="descripcion-hito" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
				<xs:element ref="galeria-fotografia" />
				<xs:element minOccurs="0" maxOccurs="1" ref="galeria-video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre-hito" type="xs:string" />
	<xs:element name="descripcion-hito" type="xs:string" />
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeria-fotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="galeria-video">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
</xs:schema>

=== sergiomalv/sew/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta nombre="Ruta del Patrimonio Cultural Eslovaco" tipo="Cultura e historia">
        <medio-transporte>A pie y autobus</medio-transporte>
        <inicio-ruta>2023-11-10T09:00:00</inicio-ruta>
        <duracion>P10D</duracion>
        <agencia>Dorado Tours</agencia>
        <descripcion>Visita los lugares más emblemáticos de Eslovaquia,
            desde los majestuosos castillos y antiguas fortalezas hasta las pintorescas ciudades y
            pueblos con encanto.</descripcion>
        <personas-adecuadas>Se puede ir con niños</personas-adecuadas>
        <lugar-inicio>Bratislava</lugar-inicio>
        <direccion-inicio>Hodžovo námestie 3</direccion-inicio>
        <coordenadas longitud="17.1067" latitud="48.1486" altitud="163"></coordenadas>
        <referencias-bibliografia> 
            <referencia-bibliografia>
                http://personatravel.com/index.php/pt/grupos/67-tour-de-eslovaquia-patrimonio-unesco</referencia-bibliografia>
            <referencia-bibliografia> https://es.wikipedia.org/wiki/Bratislava </referencia-bibliografia>
            <referencia-bibliografia>
                https://www.traveler.es/articulos/48-horas-en-bratislava-que-ver</referencia-bibliografia>
        </referencias-bibliografia>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombre-hito>Iglesia del Arcángel Miguel</nombre-hito>
                <descripcion-hito>Una iglesia histórica situado en la colina del mismo nombre, que ofrece vistas panorámicas.</descripcion-hito>
                <coordenadas longitud="18.1058" latitud="48.3194" altitud="238"></coordenadas>
                <distancia unidades="km">76</distancia>
                <galeria-fotografia>
                    <fotografia>iglesia-miguel-1.jpg</fotografia>
                    <fotografia>iglesia-miguel-2.jpg</fotografia>
                </galeria-fotografia>
            </hito>
            <hito>
                <nombre-hito>Basílica de Santiago</nombre-hito>
                <descripcion-hito>Una iglesia gótica notable en Levoca con un impresionante retablo de madera tallada.</descripcion-hito>
                <coordenadas longitud="20.5903" latitud="49.0256" altitud="578"></coordenadas>
                <distancia unidades="km">198</distancia>
                <galeria-fotografia>
                    <fotografia>basilica-santiago-1.jpg</fotografia>
                    <fotografia>basilica-santiago-2.jpg</fotografia>
                    <fotografia>basilica-santiago-3.jpg</fotografia>
                </galeria-fotografia>
                <galeria-video>
                    <video>basilica-santiago-1.mp4</video>
                </galeria-video>
            </hito>
            <hito>
                <nombre-hito>Castillo de Spis</nombre-hito>
                <descripcion-hito>Un imponente castillo declarado Patrimonio de la Humanidad por la UNESCO, situado en la región de Spis.</descripcion-hito>
                <coordenadas longitud="20.7661" latitud="48.9989" altitud="555"></coordenadas>
                <distancia unidades="km">14</distancia>
                <galeria-fotografia>
                    <fotografia>spis-castle-1.jpg</fotografia>
                </galeria-fotografia>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Ruta de los Parques Nacionales Eslovacos" tipo="Naturaleza y aventura">
        <medio-transporte>Senderismo y autobus</medio-transporte>
        <inicio-ruta>2023-11-20T08:00:00</inicio-ruta>
        <duracion>P5D</duracion>
        <agencia>All Trails</agencia>
        <descripcion>Sumérgete en la exhuberante belleza de los parques nacionales eslovecos. Desde imponentes paisajes montañosos hasta cautivadoras reservas junto a su vida silvestre.</descripcion>
        <personas-adecuadas>Personas en buena forma física</personas-adecuadas>
        <lugar-inicio>Poprad</lugar-inicio>
        <direccion-inicio>Námestie sv. Egídia 341/43</direccion-inicio>
        <coordenadas longitud="20.3042" latitud="49.0550" altitud="675"></coordenadas>
        <referencias-bibliografia>
            <referencia-bibliografia>
                https://www.alltrails.com/es/slovakia/parques-nacionales</referencia-bibliografia>
            <referencia-bibliografia> https://es.wikiloc.com/rutas/senderismo/eslovaquia-republica-eslovaca </referencia-bibliografia>
            <referencia-bibliografia>
                https://www.getyourguide.es/zakopane-l1554/rutas-por-los-altos-tatras-t62154/</referencia-bibliografia>
        </referencias-bibliografia>
        <recomendacion>7</recomendacion>
        <hitos>
            <hito>
                <nombre-hito>Belianske lúky</nombre-hito>
                <descripcion-hito>Un impresionante parque conocido por sus espectaculares prados.</descripcion-hito>
                <coordenadas longitud="20.3860" latitud="49.2127" altitud="681"></coordenadas>
                <distancia unidades="km">18</distancia>
                <galeria-fotografia>
                    <fotografia>parque-nacional-paraiso-eslovaco-1.jpg</fotografia>
                    <fotografia>parque-nacional-paraiso-eslovaco-2.jpg</fotografia>
                    <fotografia>parque-nacional-paraiso-eslovaco-3.jpg</fotografia>
                </galeria-fotografia>
            </hito>
            <hito>
                <nombre-hito>Parque Nacional de los Altos Tatras</nombre-hito>
                <descripcion-hito>La región montañosa más alta de Eslovaquia con una biodiversidad impresionante y rutas de senderismo desafiantes.</descripcion-hito>
                <coordenadas longitud="20.1301" latitud="49.1673" altitud="2050"></coordenadas>
                <distancia unidades="km">20</distancia>
                <galeria-fotografia>
                    <fotografia>parque-nacional-altos-tatras-1.jpg</fotografia>
                    <fotografia>parque-nacional-altos-tatras-2.jpg</fotografia>
                </galeria-fotografia>
            </hito>
            <hito>
                <nombre-hito>Parque Nacional del Bajo Tatras</nombre-hito>
                <descripcion-hito>Un paraíso natural que alberga bosques extensos, prados alpinos y numerosas especies de animales salvajes.</descripcion-hito>
                <coordenadas longitud="19.6534" latitud="48.8534" altitud="744"></coordenadas>
                <distancia unidades="km">49</distancia>
                <galeria-fotografia>
                    <fotografia>parque-nacional-bajo-tatras-1.jpg</fotografia>
                </galeria-fotografia>
                <galeria-video>
                    <video>parque-nacional-bajo-tatras-1.mp4</video>
                </galeria-video>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Ruta de los Tesoros Ocultos de Eslovaquia" tipo="Cultura y arqueología">
        <medio-transporte>Coche de alquiler y a pie</medio-transporte>
        <inicio-ruta>2024-02-02T09:30:00</inicio-ruta>
        <duracion>P6D</duracion>
        <agencia>Get your guide</agencia>
        <descripcion>Descubre los secretos ocultos de Eslovaquia a través de esta ruta única que te lleva a antiguas ruinas, pintorescos pueblos y fascinantes museos.</descripcion>
        <personas-adecuadas>Todos los públicos</personas-adecuadas>
        <lugar-inicio>Košice</lugar-inicio>
        <direccion-inicio>Hlavná 80</direccion-inicio>
        <coordenadas longitud="21.2560" latitud="48.7216" altitud="214"></coordenadas>
        <referencias-bibliografia>
            <referencia-bibliografia>
                https://www.getyourguide.es/bratislava-l765/tesoros-ocultos-tc268/</referencia-bibliografia>
            <referencia-bibliografia> https://es.wikipedia.org/wiki/Ko%C5%A1ice </referencia-bibliografia>
            <referencia-bibliografia>
                https://www.republica.com/dondeviajar/tesoros-ocultos-de-eslovaquia-20120321-100056912/</referencia-bibliografia>
        </referencias-bibliografia>
        <recomendacion>10</recomendacion>
        <hitos>
            <hito>
                <nombre-hito>Ruinas de Devín</nombre-hito>
                <descripcion-hito>Antiguas ruinas de un castillo en la confluencia de los ríos Danubio y Morava, que datan del siglo IX.</descripcion-hito>
                <coordenadas longitud="16.9843" latitud="48.1756" altitud="151"></coordenadas>
                <distancia unidades="km">321</distancia>
                <galeria-fotografia>
                    <fotografia>ruinas-devin-1.jpg</fotografia>
                    <fotografia>ruinas-devin-2.jpg</fotografia>
                    <fotografia>ruinas-devin-3.jpg</fotografia>
                </galeria-fotografia>
            </hito>
            <hito>
                <nombre-hito>Iglesia de madera de Hervartov</nombre-hito>
                <descripcion-hito>Una iglesia de madera gótica bien conservada y protegida por la UNESCO, que data del siglo XV.</descripcion-hito>
                <coordenadas longitud="21.2036" latitud="49.2467" altitud="462"></coordenadas>
                <distancia unidades="km">331</distancia>
                <galeria-fotografia>
                    <fotografia>iglesia-madera-hervartov-1.jpg</fotografia>
                    <fotografia>iglesia-madera-hervartov-2.jpg</fotografia>
                    <fotografia>iglesia-madera-hervartov-3.jpg</fotografia>
                </galeria-fotografia>
            </hito>
            <hito>
                <nombre-hito>Museo de la Cultura Liptov</nombre-hito>
